project:
  type: website
  output-dir: docs
website:
  title: "APL Exploration"
  navbar:
    right:
      - about.ipynb
      - icon: github
        href: https://github.com/isaac-flath/apl-exploration
      - icon: twitter
        href: https://twitter.com/isaac-flath/
format:
  html:
    css: styles.css
    toc: true
    monobackgroundcolor: '#FAFAFA'

